### ISSUE TITLE
Any update plan?

### ISSUE THREAD

**Issue by anthonycmeow** [syonip/flutter_publitio#5]
Hello Publitio Team, 

Is there any plan to update your Flutter plugin for the newest Flutter version 1.20.2 ?

Regards,

**Comment by syonip** [comment]
Hi @anthonycmeow ,
I'm not from the publitio team, I made this plugin as a simple wrapper around the native publitio SDKs, because I needed it for my project.
I don't plan to update this as I've come to the conclusion that using the API directly from the client is inherently insecure, and so I don't recommend it.
A better approach I think is to use a serverless function like I describe here: https://itnext.io/serverless-video-upload-and-encoding-with-firebase-storage-cloud-functions-and-publitio-a4b2997b1508
Source code: https://github.com/syonip/flutter_cloud_function_publitio
(this is with firebase).

If you still want to use this you can add support for new versions, I'm happy to accept a PR :)

**Comment by anthonycmeow** [comment]
@syonip Thanks for your reply, I would like to submit the PR later. Thanks again.
